import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HighRes from "../public/high-res.jpg"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          placeholder="blur"
          src={HighRes}
          alt="Man in the moon"
          width={600}
          height={200}
        />
      </main>
    </div>
  );
}